# Generated by Django 2.1.7 on 2019-04-06 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omok', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='White',
            new_name='Stone',
        ),
        migrations.DeleteModel(
            name='Black',
        ),
    ]
